### ISSUE TITLE
Add support for TweakScale.

### ISSUE THREAD

**Issue by allista** [allista/ConfigurableContainers#1]

**Comment by pellinor0** [comment]
See this post for a code example:
http://forum.kerbalspaceprogram.com/index.php?/topic/101540-12-tweakscale-v23oct-15-fixed-wheel-colliders/&do=findComment&comment=2578096

**Comment by allista** [comment]
Thanks! Though I already have it working through IRescalable interface. Would you suggest I rewrite it to use partMessage instead?

**Comment by pellinor0** [comment]
Either way is fine, those interfaces should do exactly the same thing. Just thought the part message is simpler.

**Comment by allista** [comment]
Added in v2.3 using part message.
