### ISSUE TITLE
ProceduralParts tanks have fixed dry mass

### ISSUE THREAD

**Issue by storance** [allista/ConfigurableContainers#10]
When using this mod with ProceduralParts, the ProceduralParts tanks have a fixed 1 ton dry mass no matter what size the tank.

I did a little investigating and it appears this is because the TankContentSwitcher module is what updates the tanks dry mass based on size and the module manager patch is removing it.  With the TankContentSwitcher module removed, it ends up using the mass defined in the part's config which is 1 ton.   ModularFuelTanks/RealFuels works around this by performing the dry mass calculation in it's ModuleFuelTanks module.

**Comment by allista** [comment]
You are correct in your analysis.

Unfortunately, there's nothing I can do considering this architecture. It's a pity @Swamp-Ig decided to manage mass changes **only** inside the TankContentSwitcher, which seems unreasonable given the procedural nature of the parts themselves.

What CC does unlike MFT/RF is: it only changes the *contents* of the part, not its hull. A TankType in CC can ADD to the dry mass (insulation, thicker walls, etc), but never subtract from it. And it would certainly leave the mass alone if it does not add anything except for the resource.

This is done both to allow mods like TweakScale change the part as they see fit, and to make it easier to create non-container parts that have a lot of stuff in them, including some resources. *Clearly, one wouldn't want the dry mass of such a part to be calculated purely from the contents of its tiny little resource compartment divided into several portions for, say, food and water.*

**Comment by allista** [comment]
So I propose to redirect this to [ProceduralParts](https://github.com/Swamp-Ig/ProceduralParts) repo, so that mass modification would be devided into hull (managed by the module responsible for changing geometry) and resource switching.

**Comment by Starwaster** [comment]
That is an odd response and not correct.
Of course there is something you can do. You can NOT tamper with Procedural Parts. That's a choice that you made and implemented. You didn't HAVE to do that you CHOSE to do so.

If you don't like the way that PP does its mass changes then yes by all means _propose_ a different method, but don't shift responsibility for the issue at hand because that's an issue entirely of your making.

**Comment by allista** [comment]
Are you having a bad day or something, with that kind of politeness? :)

I'm not tampering with anything; I was asked to make a patch for PP, I made one. It's not my, or (as far as I see by commits) your fault, that the current PP architecture is as it is. But the original choice to delegate mass changes was a poor one: if a module changes geometry, its responsibility is to change physical properties as well.

If you like, I can remove the patch for PP, referencing your decision about it.

Or, if you prefer to retain support of Configurable Containers, I can collaborate on the appropriate changes in PP. But I would definitely not do it without your good will and discussion beforehand. Silent fork+PR would be tampering indeed.

**Comment by Starwaster** [comment]
I could have done with a more politic response but chose a more straightforward and in my view, unequivocal statement given that I'm getting support requests for an issue and tracing it back to CC find that PP itself is implicated as to cause.

If the two mods are in some way interfering with each other with regards to mass setting then by all means raise an issue over it and we'll talk about it. Or go ahead and remove the module TankContentSwitcher but then take responsibility for the part's (now) static mass and adjust it in CC. It doesn't so much bother me that the module was removed so much as the situation was then left like that and responsibility shifted away.

There's numerous ways that this can be handled.

**Comment by allista** [comment]
Ok. So what do you propose we do if we want to properly support each other's mods? Is there anything that could be done aside from changing PP code or replicating its mass calculation in CC?

**Comment by Starwaster** [comment]
I think I need to know first what you were trying to solve by removing the module in question

**Comment by allista** [comment]
Resource switching that the added CC module does instead.

**Comment by Starwaster** [comment]
This may need some additional modification or maybe some alteration of PP code but here's what I have so far that works. (I'm not familiar with CC so I'm not sure if it's working the way it's supposed to work. Something seems off and I don't know if it's my lack of familiarity or not. When I add resources with the CC editor, they're empty initially and I have to use the slider bar. Is that working as intended?)

First, don't delete TankContentSwitcher. Instead, delete all TANK_TYPE_OPTION from within the node and replace with one that doesn't manage resources.

Example below. Edit density to suit. Name can be whatever, I called it Configurable Container

```
	@MODULE[TankContentSwitcher]
	{
		!TANK_TYPE_OPTION[*],*{}
		TANK_TYPE_OPTION
		{
			name = Configurable Container
			dryDensity = 0.05
			isStructural = true
		}
	}

```

**Comment by HebaruSan** [comment]
Maybe you could make the patch that modifies PP's tanks optional with PatchManager?
http://forum.kerbalspaceprogram.com/index.php?/topic/163072-13-patchmanager/
That way people who install both mods could choose how to handle this conflict.
