### ISSUE TITLE
Add support for Snacks!

### ISSUE THREAD

**Issue by LouisCyfer** [allista/ConfigurableContainers#17]
As proposed [here](https://forum.kerbalspaceprogram.com/index.php?/topic/150104-13-configurable-containers/&do=findComment&comment=3160603) Snacks might be cool to have in CC

Either adding a simple new category "SnacksLS" or one that is rather complex but more reasonable, both will do the job.

#### first way:
* add this at
https://github.com/allista/ConfigurableContainers/blob/a2eab81ee66d20e4dd09ee562453dfbe05b78e5e/GameData/ConfigurableContainers/TankTypes.cfg#L187
```C
TANKTYPE:NEEDS[Snacks] 
{
	name = SnacksLS
	UsefulVolumeRatio = 0.95
	TankCostPerSurface = 2
	AddMassPerVolume = 0.003
	PossibleResources = Snacks 1; Soil 1;
}
```
* and this at (basicially at the end)
https://github.com/allista/ConfigurableContainers/blob/a2eab81ee66d20e4dd09ee562453dfbe05b78e5e/GameData/ConfigurableContainers/TankConfigs.cfg#L64
```C
TANKCONF:NEEDS[Snacks]
{
	name = Snacks and Soil
	TANK
	{
		TankType = SnacksLS
		CurrentResource = Snacks
		InitialAmount = 1
		Volume = 50
	}
	TANK
	{
		TankType = SnacksLS
		CurrentResource = Soil
		InitialAmount = 0
		Volume = 50
	}
}
```

#### second way:
* modify the Soil definition like this (I'm still unable to make the specific Soil --> Soil from Snacks! mod have UsefulVolumeRatio = 0.95, please help me out there)
```C
TANKTYPE
{
	name = Soil
	UsefulVolumeRatio = 1
	TankCostPerSurface = 2
	PossibleResources = Ore 0.185; //cfd
}
@TANKTYPE[Soil]:NEEDS[KolonyTools] //cfd
{ @PossibleResources ^= :$: Dirt 1; Mulch 1; Fertilizer 1; ExoticMinerals 1; MetallicOre 1; Substrate 1; Minerals 1; Polymers 1; Hydrates 1; Gypsum 1; Silicates 1; Silicon 1; Organics 1; RefinedExotics  1;: }
@TANKTYPE[Soil]:NEEDS[WarpPlugin]
{ @PossibleResources ^= :$: Alumina 1;: } //cfd
@TANKTYPE[Soil]:NEEDS[Launchpad]
{ @PossibleResources ^= :$: MetalOre 0.7;: } //cfd
// @TANKTYPE[Soil]:NEEDS[Snacks]
// { @PossibleResources ^= :$: Soil 1;: }

// unsure how to implent the UsefulVolumeRatio = 0.95 Soil has same values as Snacks
TANKTYPE:NEEDS[Snacks] 
{
	name = Soil
	UsefulVolumeRatio = 0.95 // has same values as Snacks - arb
	PossibleResources = Soil 1;
}
```
* modify this line
https://github.com/allista/ConfigurableContainers/blob/a2eab81ee66d20e4dd09ee562453dfbe05b78e5e/GameData/ConfigurableContainers/TankTypes.cfg#L173
```C
TANKTYPE:NEEDS[TacLifeSupport|USILifeSupport|Snacks] //arb
```
* add this at
https://github.com/allista/ConfigurableContainers/blob/a2eab81ee66d20e4dd09ee562453dfbe05b78e5e/GameData/ConfigurableContainers/TankTypes.cfg#L187
```C
@TANKTYPE[Food]:NEEDS[Snacks] // SnacksLS - arb
{ @PossibleResources ^= :$: Snacks 1;: }
```
* and this at (basicially at the end)
https://github.com/allista/ConfigurableContainers/blob/a2eab81ee66d20e4dd09ee562453dfbe05b78e5e/GameData/ConfigurableContainers/TankConfigs.cfg#L64
```C
TANKCONF:NEEDS[Snacks]
{
	name = Snacks and Soil
	TANK
	{
		TankType = Food
		CurrentResource = Snacks
		InitialAmount = 1
		Volume = 50
	}
	TANK
	{
		TankType = Soil
		CurrentResource = Soil
		InitialAmount = 0
		Volume = 50
	}
}
```

ty for your time!

**Comment by allista** [comment]
Added in last release.
