### ISSUE TITLE
Tweakscaled tanks have volume scaling reapplied each save/load cycle

### ISSUE THREAD

**Issue by Atario** [allista/ConfigurableContainers#22]
Steps:

1.  Have Tweakscale installed
1.  Go to VAB/SPH
1.  New vessel
1.  Add a CC-ed container (Example:  Rockomax X200-16)
1.  Note default scale and volume (Ex.:  2.5m and 9.9m3)
1.  Rescale to some other size (Ex.:  5m)
1.  Note new volume (Ex.:  79.0m3 — 8× previous, as expected)
1.  Save vessel
1.  Load vessel
1.  Note new volume (Ex.:  **Expected** = 79.0m3 — unchanged.  **Actual** = 632.1m3 — 8× previous again)
1.  Repeat save/load for repeatedly multiplied new volume figures (Ex.:  5,056.8m3, 40,454.3m3, …)

**Comment by allista** [comment]
Fixed. Wait for an update.
