### ISSUE TITLE
ArgumentOutOfRangeException when building symmetry tanks

### ISSUE THREAD

**Issue by andylizi** [allista/ConfigurableContainers#31]
### Environment
* KSP version 1.5.1.2335 (WindowsPlayer x64) zh-cn
* Making History DLC 1.5.1
* Mods - I stripped all mods expect the following
  * AT_Utils 1.6.2
  * Configurable Containers 2.4.3.4
  * Configurable Containers Core 2.4.3.4

### Description
```
[EXC] ArgumentOutOfRangeException: Argument is out of range.
Parameter name: index
	System.Collections.Generic.List`1[PartResource].get_Item (Int32 index)
	DictionaryValueList`2[System.Int32,PartResource].At (Int32 index)
	PartResourceList.get_Item (Int32 index)
	Part.OnCopy (.Part original, Boolean asSymCounterpart)
	EditorLogic.createSymmetry (Int32 mode, .Attachment attach)
	EditorLogic.<SetupFSM>m__D ()
	KerbalFSM.UpdateFSM ()
	EditorLogic.Update ()
```
I'm not very good at English, so I'll just refer to [this forum post](https://forum.kerbalspaceprogram.com/index.php?/topic/179432-vab-symmetry-issue/) reporting the same issue.
When I uninstall Configurable Containers the bug disappeared.
For testing purposes, only this mod is installed, so it can't be a mod conflict.

### Steps to reproduce
![](https://user-images.githubusercontent.com/12008103/49679114-e574bd80-fac3-11e8-898b-71474730eadc.png)
1. Place an 4x symmetry radial decoupler on any part.
2. Try to place any type of tank (with 4x symmetry) on the decoupler.
3. Exception occurs and you only get one tank.

**Comment by RealKolago** [comment]
I can confirm, this happens when trying to attach CC tanks with symmetry over 2!
