### ISSUE TITLE
incompatibility with space y heavy lifters , faulty volume calculation

### ISSUE THREAD

**Issue by tonimark** [allista/ConfigurableContainers#34]
i had a rocket with spaxe Y expanded mod but the contents got from 50 Kg of oxidizer and 40Kg liquid fuel into 5kg of oxidizer and 4kg of liquid fuel , the rocket can't now launch into space and requires a complete rebuilt

**Comment by tonimark** [comment]
happened after the last update

**Comment by allista** [comment]
This is very strange, considering the **code**  haven't been changed in a long time. I'll need the .craft file and the list of mods to reproduce.

**Comment by tonimark** [comment]
a note: a new placed tank with show the real contents of the tank but the mod will decrease it like the real fuels mod (which is not installed) maybe you messed up an integration or something

**Comment by tonimark** [comment]
to reproduce just built a spacey  expanded (expansion of spacy lifters) tank and launch it, you will notice a much smaller fuel capacity

**Comment by allista** [comment]
Still, please, provide the .craft + mod list, preferably in .ckan format.

**Comment by tonimark** [comment]
by the way neither  .ckan  or .craft files are not supported by GitHub , so how do i sent them ?

**Comment by tonimark** [comment]
here:[files.zip](https://github.com/allista/ConfigurableContainers/files/4557199/files.zip)
note CKAN doesn't write autodetected mods in its ckan. file

**Comment by tonimark** [comment]
i just noticed that that also happens with spacey mod itself not only his addon and a typical size 3 fuel tank contains 50% more fuel than the space y heavy lifters size 4 tanks indicating faulty volume calculation for the space y tanks I can still bypass the issue if I used resized size 3 tanks

**Comment by allista** [comment]
So far was unable to reproduce any of this. Space-Y Lifters and Extended tanks all have the exact same amount of resources with CC as in vanilla installation.
